import fs from "node:fs";
import path from "node:path";
import * as yaml from "js-yaml";

const SPEC_FILE = path.join(process.cwd(), "openapi.yaml");
const OUT_FILE = path.join(process.cwd(), "src/api/endpoints.ts");

const HTTP_METHODS = ["get", "put", "post", "delete", "options", "head", "patch", "trace"] as const;

interface OpenAPIParameter {
  name: string;
  in: string;
  required?: boolean;
  description?: string;
  schema?: { type?: string; example?: unknown; enum?: unknown[] };
}

interface OpenAPIOperation {
  operationId: string;
  summary?: string;
  description?: string;
  tags?: string[];
  security?: unknown[];
  parameters?: (OpenAPIParameter | { $ref: string })[];
  requestBody?: {
    description?: string;
    content?: Record<string, { schema?: { $ref?: string } }>;
  };
  responses?: Record<
    string,
    { description?: string; content?: Record<string, { schema?: { $ref?: string } }> }
  >;
}

interface OpenAPISpec {
  info: { title: string; version: string; description?: string };
  paths: Record<string, Record<string, OpenAPIOperation>>;
  components?: {
    parameters?: Record<string, OpenAPIParameter>;
  };
}

export interface EndpointParameter {
  name: string;
  location: string;
  required: boolean;
  description?: string;
  type?: string;
  example?: unknown;
  enum?: unknown[];
}

export interface EndpointManifestEntry {
  operationId: string;
  method: string;
  path: string;
  tags: string[];
  summary?: string;
  description?: string;
  requiresAuth: boolean;
  parameters: EndpointParameter[];
  requestSchema: string | null;
  responseSchema: string | null;
  successDescription?: string;
}

function resolveRef(ref: string): string {
  return ref.replace("#/components/schemas/", "");
}

function resolveParameter(
  param: OpenAPIParameter | { $ref: string },
  spec: OpenAPISpec
): OpenAPIParameter {
  if ("$ref" in param) {
    const name = param.$ref.replace("#/components/parameters/", "");
    const resolved = spec.components?.parameters?.[name];
    if (!resolved) {
      throw new Error(`Unresolved parameter ref: ${param.$ref}`);
    }
    return resolved;
  }
  return param;
}

function buildManifest(spec: OpenAPISpec): EndpointManifestEntry[] {
  const entries: EndpointManifestEntry[] = [];

  for (const [pathKey, operations] of Object.entries(spec.paths)) {
    for (const method of HTTP_METHODS) {
      const operation = operations[method];
      if (!operation) continue;

      const parameters = (operation.parameters ?? []).map((param) => {
        const resolved = resolveParameter(param, spec);
        return {
          name: resolved.name,
          location: resolved.in,
          required: resolved.required ?? false,
          description: resolved.description,
          type: resolved.schema?.type,
          example: resolved.schema?.example,
          enum: resolved.schema?.enum,
        };
      });

      const requestContent = operation.requestBody?.content?.["application/json"];
      const requestSchema = requestContent?.schema?.$ref
        ? resolveRef(requestContent.schema.$ref)
        : null;

      const successResponse = operation.responses?.["200"];
      const responseContent = successResponse?.content?.["application/json"];
      const responseSchema = responseContent?.schema?.$ref
        ? resolveRef(responseContent.schema.$ref)
        : null;

      entries.push({
        operationId: operation.operationId,
        method: method.toUpperCase(),
        path: pathKey,
        tags: operation.tags ?? [],
        summary: operation.summary,
        description: operation.description?.trim(),
        requiresAuth: Boolean(operation.security && operation.security.length > 0),
        parameters,
        requestSchema,
        responseSchema,
        successDescription: successResponse?.description?.trim(),
      });
    }
  }

  return entries.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
}

function main() {
  const raw = fs.readFileSync(SPEC_FILE, "utf8");
  const spec = yaml.load(raw) as OpenAPISpec;
  const manifest = buildManifest(spec);

  const banner = `// This file is generated by \`pnpm run build-manifest\` from \`openapi.yaml\`.\n// Do not edit by hand - regenerate with \`pnpm run update\`.\n`;
  const body = `export interface EndpointParameter {
  name: string;
  location: string;
  required: boolean;
  description?: string;
  type?: string;
  example?: unknown;
  enum?: unknown[];
}

export interface EndpointManifestEntry {
  operationId: string;
  method: string;
  path: string;
  tags: string[];
  summary?: string;
  description?: string;
  requiresAuth: boolean;
  parameters: EndpointParameter[];
  requestSchema: string | null;
  responseSchema: string | null;
  successDescription?: string;
}

export const API_INFO = ${JSON.stringify({ title: spec.info.title, version: spec.info.version }, null, 2)} as const;

export const ENDPOINT_MANIFEST: EndpointManifestEntry[] = ${JSON.stringify(manifest, null, 2)};
`;

  fs.writeFileSync(OUT_FILE, banner + "\n" + body);
  console.log(`Wrote ${manifest.length} endpoint entries to ${OUT_FILE}`);
}

main();
