// This file is generated by `pnpm run build-manifest` from `openapi.yaml`.
// Do not edit by hand - regenerate with `pnpm run update`.

export interface EndpointParameter {
  name: string;
  location: string;
  required: boolean;
  description?: string;
  type?: string;
  example?: unknown;
  enum?: unknown[];
}

export interface EndpointManifestEntry {
  operationId: string;
  method: string;
  path: string;
  tags: string[];
  summary?: string;
  description?: string;
  requiresAuth: boolean;
  parameters: EndpointParameter[];
  requestSchema: string | null;
  responseSchema: string | null;
  successDescription?: string;
}

export const API_INFO = {
  "title": "Tebex Headless API",
  "version": "2.0.0"
} as const;

export const ENDPOINT_MANIFEST: EndpointManifestEntry[] = [
  {
    "operationId": "getWebstore",
    "method": "GET",
    "path": "/",
    "tags": [
      "Headless"
    ],
    "summary": "Get the webstore's information",
    "description": "Gets the webstore associated with the provided token",
    "requiresAuth": false,
    "parameters": [],
    "requestSchema": null,
    "responseSchema": "WebstoreResponse",
    "successDescription": "Successful response returns the webstore's information."
  },
  {
    "operationId": "addBasketPackage",
    "method": "POST",
    "path": "/{basketIdent}/packages",
    "tags": [
      "Baskets"
    ],
    "summary": "Add package to basket",
    "description": "Add a package with the given ID to the basket.\n\nTo add a package belonging to a dynamic category, set `dynamic` to `true`. Without this property the API will treat the request as a normal package ID.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": "Basket",
    "successDescription": "Successful response."
  },
  {
    "operationId": "updatePackageQuantity",
    "method": "PUT",
    "path": "/{basketIdent}/packages/{packageId}",
    "tags": [
      "Baskets"
    ],
    "summary": "Update package quantity",
    "description": "Sets the quantity of the given item in the basket. The user must be logged in before the quantity can be changed.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": null,
    "successDescription": "Successful response."
  },
  {
    "operationId": "removeBasketPackage",
    "method": "POST",
    "path": "/{basketIdent}/packages/remove",
    "tags": [
      "Baskets"
    ],
    "summary": "Remove a package from a basket",
    "description": "Remove the given package ID from the basket.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": "Basket",
    "successDescription": "Successful response returns the basket."
  },
  {
    "operationId": "createBasket",
    "method": "POST",
    "path": "/baskets",
    "tags": [
      "Headless"
    ],
    "summary": "Create a new basket",
    "description": "Creates a new basket for use during checkout.",
    "requiresAuth": false,
    "parameters": [],
    "requestSchema": null,
    "responseSchema": "BasketResponse",
    "successDescription": "Successful response returns the basket information."
  },
  {
    "operationId": "getBasket",
    "method": "GET",
    "path": "/baskets/{basketIdent}",
    "tags": [
      "Headless"
    ],
    "summary": "Get a basket",
    "description": "Gets a basket associated with the provided identifier.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": "BasketResponse",
    "successDescription": "Successful response returns the basket information."
  },
  {
    "operationId": "getBasketAuthUrl",
    "method": "GET",
    "path": "/baskets/{basketIdent}/auth?returnUrl={returnUrl}",
    "tags": [
      "Headless"
    ],
    "summary": "Get auth links for basket",
    "description": "Fetches a basket's auth URL. The player should be directed here in order for them to authorize their account.\nWhen complete, they will be returned to the provided `returnUrl` and the basket will be authorized from that moment onwards.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      },
      {
        "name": "returnUrl",
        "location": "path",
        "required": true,
        "description": "The URL you would like to redirect the user to after successful basket authentication.",
        "type": "string",
        "example": "https://example.tebex.io/"
      }
    ],
    "requestSchema": null,
    "responseSchema": "BasketAuthResponse",
    "successDescription": "Successful response returns the auth provider options and URLs of the sign-in link."
  },
  {
    "operationId": "applyCoupon",
    "method": "POST",
    "path": "/baskets/{basketIdent}/coupons",
    "tags": [
      "Headless"
    ],
    "summary": "Apply a coupon",
    "description": "Applies a coupon to a basket.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": "ApplyCouponRequest",
    "responseSchema": null,
    "successDescription": "Successful response returns a success message."
  },
  {
    "operationId": "removeCoupon",
    "method": "POST",
    "path": "/baskets/{basketIdent}/coupons/remove",
    "tags": [
      "Headless"
    ],
    "summary": "Remove a coupon from the basket.",
    "description": "Removes a coupon code from a basket",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": "ApplyCouponRequest",
    "responseSchema": null,
    "successDescription": "Successful response."
  },
  {
    "operationId": "applyCreatorCode",
    "method": "POST",
    "path": "/baskets/{basketIdent}/creator-codes",
    "tags": [
      "Headless"
    ],
    "summary": "Apply a creator code",
    "description": "Applies a creator code to a basket.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": null,
    "successDescription": "Successful response returns a success object"
  },
  {
    "operationId": "removeCreatorCode",
    "method": "POST",
    "path": "/baskets/{basketIdent}/creator-codes/remove",
    "tags": [
      "Headless"
    ],
    "summary": "Removes the creator code from the basket.",
    "description": "Removes the creator code from the basket.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": null,
    "successDescription": "Creator code removed successfully."
  },
  {
    "operationId": "createDynamicPackage",
    "method": "PUT",
    "path": "/baskets/{basketIdent}/dynamic-packages",
    "tags": [
      "Headless"
    ],
    "summary": "Add packages to a dynamic category for a basket.",
    "description": "Populates a dynamic category with custom packages for the given basket. Dynamic categories are created in the creator panel with the type `dynamic`, and are typically populated in response to a `basket.authenticated` webhook.\n\nOnce created, the packages can be fetched using the category endpoints with both `includePackages=1` and `basketIdent` provided.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": "DynamicPackagesRequest",
    "responseSchema": "DynamicPackagesResponse",
    "successDescription": "Successful response confirms the dynamic packages were created."
  },
  {
    "operationId": "applyGiftCard",
    "method": "POST",
    "path": "/baskets/{basketIdent}/giftcards",
    "tags": [
      "Headless"
    ],
    "summary": "Apply a gift card",
    "description": "Applies a gift card to the basket.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": "GiftCard",
    "responseSchema": null,
    "successDescription": "Successful response returns a success message."
  },
  {
    "operationId": "removeGiftCard",
    "method": "POST",
    "path": "/baskets/{basketIdent}/giftcards/remove",
    "tags": [
      "Headless"
    ],
    "summary": "Remove a gift card from the basket.",
    "description": "Removes a gift card from the basket.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": null,
    "successDescription": "Gift card removed successfully."
  },
  {
    "operationId": "getCategories",
    "method": "GET",
    "path": "/categories",
    "tags": [
      "Headless"
    ],
    "summary": "Get all categories",
    "description": "Gets all categories from a webstore. This does not include package information. To include package information, add `?includePackages=1` to the URL.",
    "requiresAuth": false,
    "parameters": [],
    "requestSchema": null,
    "responseSchema": "CategoryResponse",
    "successDescription": "Successful response returns a list of category information."
  },
  {
    "operationId": "getCategoriesIncludePackages",
    "method": "GET",
    "path": "/categories?includePackages=1",
    "tags": [
      "Headless"
    ],
    "summary": "Gets all categories and packages",
    "description": "Gets all categories from a webstore including packages.",
    "requiresAuth": false,
    "parameters": [],
    "requestSchema": null,
    "responseSchema": "CategoryResponse",
    "successDescription": "Successful response returns a list of category information."
  },
  {
    "operationId": "getDynamicCategories",
    "method": "GET",
    "path": "/categories?includePackages=1&basketIdent={basketIdent}",
    "tags": [
      "Headless"
    ],
    "summary": "Get Dynamic Categories",
    "description": "Gets all categories from a webstore including packages. When `basketIdent` is provided, dynamic categories are populated with the packages associated with that basket.\n\nIf a basket identifier is not provided, dynamic categories will be empty as the basket is required to relate packages to the category.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": "CategoryResponse",
    "successDescription": "Successful response returns a list of category information."
  },
  {
    "operationId": "getUserTieredCategories",
    "method": "GET",
    "path": "/categories?usernameId={usernameId}&includePackages=1",
    "tags": [
      "Headless"
    ],
    "summary": "Get user's tiered categories",
    "description": "Gets all categories from the webstore, returning active tier information for the given player.",
    "requiresAuth": true,
    "parameters": [
      {
        "name": "usernameId",
        "location": "path",
        "required": true,
        "type": "integer",
        "example": 76561198042467020
      }
    ],
    "requestSchema": null,
    "responseSchema": "CategoryResponse",
    "successDescription": "Successful response returns a list of category information."
  },
  {
    "operationId": "getCategory",
    "method": "GET",
    "path": "/categories/{categoryId}",
    "tags": [
      "Headless"
    ],
    "summary": "Get specific category",
    "description": "Gets information about a category and returns the packages in that category.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": "CategoryResponse",
    "successDescription": "Successful response returns the category without package information."
  },
  {
    "operationId": "getCategoryIncludePackages",
    "method": "GET",
    "path": "/categories/{categoryId}?includePackages=1",
    "tags": [
      "Headless"
    ],
    "summary": "Get a category with all packages",
    "description": "Gets information about a category and returns the packages in that category.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "categoryId",
        "location": "path",
        "required": true,
        "description": "The ID or slug of the category to fetch.",
        "type": "string",
        "example": 127244343
      }
    ],
    "requestSchema": null,
    "responseSchema": "CategoryResponse",
    "successDescription": "Successful response returns the category with package information."
  },
  {
    "operationId": "getCategoryIncludeDynamicPackages",
    "method": "GET",
    "path": "/categories/{categoryId}?includePackages=1&basketIdent={basketIdent}",
    "tags": [
      "Headless"
    ],
    "summary": "Gets a specific category including packages, populating a dynamic category for the given basket.",
    "description": "Gets information about a category and returns the packages in that category. When the category is dynamic and `basketIdent` is provided, the category is populated with the packages associated with that basket.\n\nIf a basket identifier is not provided, a dynamic category will be empty as the basket is required to relate packages to the category.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "categoryId",
        "location": "path",
        "required": true,
        "description": "The ID or slug of the category to fetch.",
        "type": "string",
        "example": 1234
      },
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": "CategoryResponse",
    "successDescription": "Successful response returns the category with package information."
  },
  {
    "operationId": "getAllPackages",
    "method": "GET",
    "path": "/packages",
    "tags": [
      "Headless"
    ],
    "summary": "Get all packages",
    "description": "Gets all packages from a webstore.\n\nNote: this endpoint does not support packages belonging to dynamic categories. Use the category endpoints with `includePackages=1` and `basketIdent` to fetch dynamic packages.",
    "requiresAuth": false,
    "parameters": [],
    "requestSchema": null,
    "responseSchema": "PackageResponse",
    "successDescription": "Successful response returns a list of package information."
  },
  {
    "operationId": "getPackagesForBasket",
    "method": "GET",
    "path": "/packages?basketIdent={basketIdent}",
    "tags": [
      "Headless"
    ],
    "summary": "Get packages available for basket",
    "description": "Gets all packages available to the provided basket.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      }
    ],
    "requestSchema": null,
    "responseSchema": "PackageResponse",
    "successDescription": "Successful response returns a list of package information."
  },
  {
    "operationId": "getAllPackagesWithAuthedIP",
    "method": "GET",
    "path": "/packages?ipAddress={ipAddress}",
    "tags": [
      "Headless"
    ],
    "summary": "Get packages",
    "description": "Gets all packages from a webstore.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "ipAddress",
        "location": "path",
        "required": true,
        "description": "An IP address can be provided with authenticated requests",
        "type": "string",
        "example": "127.0.0.1"
      }
    ],
    "requestSchema": null,
    "responseSchema": "PackageResponse",
    "successDescription": "Successful response returns a list of package information."
  },
  {
    "operationId": "getAllPackagesWithAuthedIPAndBasket",
    "method": "GET",
    "path": "/packages?ipAddress={ipAddress}&basketIdent={basketIdent}",
    "tags": [
      "Headless"
    ],
    "summary": "Get packages available for IP and basket",
    "description": "Gets all packages from a webstore.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "basketIdent",
        "location": "path",
        "required": true,
        "description": "The basket identifier.",
        "type": "string",
        "example": "c00244-d2ac2e77418a55b25292a6bc7a719ad9c529ba2c"
      },
      {
        "name": "ipAddress",
        "location": "path",
        "required": true,
        "description": "An IP address can be provided with authenticated requests.",
        "type": "string",
        "example": "127.0.0.1"
      }
    ],
    "requestSchema": null,
    "responseSchema": "PackageResponse",
    "successDescription": "Successful response returns a list of package information."
  },
  {
    "operationId": "getPackage",
    "method": "GET",
    "path": "/packages/{packageId}",
    "tags": [
      "Headless"
    ],
    "summary": "Get package",
    "description": "Gets a package from a webstore by its ID or slug.\n\nNote: this endpoint does not support packages belonging to dynamic categories. Use the category endpoints with `includePackages=1` and `basketIdent` to fetch dynamic packages.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "packageId",
        "location": "path",
        "required": true,
        "description": "The package's ID or slug.",
        "type": "string",
        "example": 1272441812
      }
    ],
    "requestSchema": null,
    "responseSchema": "PackageResponse",
    "successDescription": "Successful response returns the package information."
  },
  {
    "operationId": "getCustomPages",
    "method": "GET",
    "path": "/pages",
    "tags": [
      "Headless"
    ],
    "summary": "Get custom pages defined for the webstore.",
    "description": "Gets a list of custom pages associated with the webstore. These contain a `content` variable with the HTML content of the page.",
    "requiresAuth": false,
    "parameters": [],
    "requestSchema": null,
    "responseSchema": "CMSPagesResponse",
    "successDescription": "Successful response returns the webstore's pages."
  },
  {
    "operationId": "getSidebar",
    "method": "GET",
    "path": "/sidebar",
    "tags": [
      "Headless"
    ],
    "summary": "Retrieves the available sidebar modules.",
    "description": "Retrieves the available sidebar modules configured for the store.",
    "requiresAuth": false,
    "parameters": [
      {
        "name": "token",
        "location": "path",
        "required": true,
        "description": "The webstore identifier.",
        "type": "string",
        "example": "some-uuid"
      }
    ],
    "requestSchema": null,
    "responseSchema": "ModulesResponse",
    "successDescription": "Successful response."
  },
  {
    "operationId": "updateTier",
    "method": "PATCH",
    "path": "/tiers/{tierId}",
    "tags": [
      "Headless"
    ],
    "summary": "Update user's tier to a new package",
    "description": "Updates a tier to a new package. A recurring payment updated webhook is sent when an update is successful.",
    "requiresAuth": true,
    "parameters": [
      {
        "name": "tierId",
        "location": "path",
        "required": true,
        "description": "The tier identifier",
        "type": "integer",
        "example": 6276316
      }
    ],
    "requestSchema": null,
    "responseSchema": "UpdateTierResponse",
    "successDescription": "Successful response."
  }
];
